### ISSUE TITLE
'yarn start' failed

### ISSUE THREAD

**Issue by briteming** [formula1/NodeOS-Blog#6]
~/NodeOS-Blog (master)$ yarn start
yarn run v1.22.22
node index.js
compiling all
node:internal/errors:540
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.dirname (node:path:732:5)
    at Deps.lookupPackage (C:\Users\12799\NodeOS-Blog\node_modules\module-deps\index.js:452:29)
    at Deps._transform (C:\Users\12799\NodeOS-Blog\node_modules\module-deps\index.js:93:10)
    at Transform._read (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at Pipeline._write (C:\Users\12799\NodeOS-Blog\node_modules\stream-splicer\index.js:73:22)
    at doWrite (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\lib\_stream_writable.js:279:12)
    at writeOrBuffer (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\lib\_stream_writable.js:266:5)
    at Writable.write (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\lib\_stream_writable.js:211:11)
    at Labeled.ondata (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\lib\_stream_readable.js:572:20) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v23.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/NodeOS-Blog (master)$ 

how to fix it?
tks!

**Comment by piranna** [comment]
Use `npm` instead of `yarn`.

**Comment by briteming** [comment]
@piranna ，actually this time ,i ran "node index.js" but the same error happened.

~/NodeOS-Blog (master)$ node index.js
compiling all
node:internal/errors:540
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Re
ceived undefined
    at Object.dirname (node:path:732:5)
    at Deps.lookupPackage (C:\Users\12799\NodeOS-Blog\node_modules\module-deps\i
ndex.js:452:29)
    at Deps._transform (C:\Users\12799\NodeOS-Blog\node_modules\module-deps\inde
x.js:93:10)
    at Transform._read (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\
lib\_stream_transform.js:184:10)
    at Transform._write (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream
\lib\_stream_transform.js:172:12)
    at Pipeline._write (C:\Users\12799\NodeOS-Blog\node_modules\stream-splicer\i
ndex.js:73:22)
    at doWrite (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\lib\_str
eam_writable.js:279:12)
    at writeOrBuffer (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\li
b\_stream_writable.js:266:5)
    at Writable.write (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\l
ib\_stream_writable.js:211:11)
    at Labeled.ondata (C:\Users\12799\NodeOS-Blog\node_modules\readable-stream\l
ib\_stream_readable.js:572:20) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v23.3.0

~/NodeOS-Blog (master)$

how to fix it?
thank u very much

**Comment by piranna** [comment]
It has been a long time i don't use this. Also, i have not tested It on Windows. I would suggest you to follow Up the stacktrace and debug why the path gets undefined, and if so, send a PR.
